BEGIN;

CREATE TYPE PUBLIC.MEAL_TYPE AS ENUM('lunch', 'dinner');

ALTER TYPE PUBLIC.MEAL_TYPE OWNER TO POSTGRES;

CREATE TYPE PUBLIC.SUBSCRIPTION_TYPE AS ENUM('monthly', 'one_off');

ALTER TYPE PUBLIC.SUBSCRIPTION_TYPE OWNER TO POSTGRES;

CREATE TYPE PUBLIC.PYMNT_STATUS AS ENUM(
	'pending_acknowledgement',
	'confirmed',
	'rejected'
);

ALTER TYPE PUBLIC.PYMNT_STATUS OWNER TO POSTGRES;

CREATE TYPE PUBLIC.TXN_TYPE AS ENUM('recharge', 'delivery', 'refund');

ALTER TYPE PUBLIC.TXN_TYPE OWNER TO POSTGRES;

CREATE TYPE PUBLIC.USER_TYPE AS ENUM('normal', 'admin');

ALTER TYPE PUBLIC.USER_TYPE OWNER TO POSTGRES;

CREATE TABLE IF NOT EXISTS PUBLIC.EXPENSES (
	EXPENSE_ID SERIAL NOT NULL,
	EXPENSE_DATE DATE NOT NULL,
	REASON TEXT COLLATE PG_CATALOG."default" NOT NULL,
	AMOUNT NUMERIC(10, 2) NOT NULL,
	CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
	CONSTRAINT EXPENSES_PKEY PRIMARY KEY (EXPENSE_ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.MEAL_PRICE_HISTORY (
	ITEM_ID SERIAL NOT NULL,
	ITEM_NAME TEXT COLLATE PG_CATALOG."default" NOT NULL,
	PRICE NUMERIC(10, 2) NOT NULL,
	EFFECTIVE_FROM TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
	CREATED_BY TEXT COLLATE PG_CATALOG."default",
	CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
	CONSTRAINT MEAL_PRICE_HISTORY_PKEY PRIMARY KEY (ITEM_ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.USERS (
	USER_ID SERIAL NOT NULL,
	NAME TEXT COLLATE PG_CATALOG."default",
	MOBILE_NO TEXT COLLATE PG_CATALOG."default",
	COUNTRY TEXT COLLATE PG_CATALOG."default",
	STATE TEXT COLLATE PG_CATALOG."default",
	CITY TEXT COLLATE PG_CATALOG."default",
	STREET TEXT COLLATE PG_CATALOG."default",
	BUILDING_OR_ORG TEXT COLLATE PG_CATALOG."default",
	BUILDING_NO TEXT COLLATE PG_CATALOG."default",
	ROOM_NO TEXT COLLATE PG_CATALOG."default",
	PASSWORD TEXT COLLATE PG_CATALOG."default",
	ROLE USER_TYPE DEFAULT 'normal'::USER_TYPE,
	PLAN SUBSCRIPTION_TYPE NOT NULL,
	CONSTRAINT USERS_PKEY PRIMARY KEY (USER_ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.WALLET_TRANSACTIONS (
	TXN_ID SERIAL NOT NULL,
	USER_ID INTEGER NOT NULL,
	TXN_DATE DATE DEFAULT NOW(),
	TXN_TYPE TXN_TYPE NOT NULL,
	MEAL_TYPE MEAL_TYPE NOT NULL,
	IS_SPECIAL BOOLEAN NOT NULL DEFAULT FALSE,
	SPECIAL_DISH_NAME TEXT COLLATE PG_CATALOG."default",
	EXTRA_RICE_QTY INTEGER NOT NULL DEFAULT 0,
	EXTRA_ROTI_QTY INTEGER NOT NULL DEFAULT 0,
	HAS_MAIN_MEAL BOOLEAN DEFAULT TRUE,
	EXTRA_CHICKEN_QTY INTEGER DEFAULT 0,
	EXTRA_FISH_QTY INTEGER DEFAULT 0,
	EXTRA_EGG_QTY INTEGER DEFAULT 0,
	EXTRA_VEGETABLE_QTY INTEGER DEFAULT 0,
	PAYMENT_STATUS PYMNT_STATUS NOT NULL DEFAULT 'pending_acknowledgement'::PYMNT_STATUS,
	AMOUNT NUMERIC(10, 2) NOT NULL,
	REFERENCE_ID TEXT COLLATE PG_CATALOG."default",
	CONSTRAINT WALLET_TRANSACTIONS_PKEY PRIMARY KEY (TXN_ID)
);

ALTER TABLE IF EXISTS PUBLIC.WALLET_TRANSACTIONS
ADD CONSTRAINT WALLET_TRANSACTIONS_USER_ID_FKEY FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS (USER_ID) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;

CREATE INDEX IF NOT EXISTS IDX_WALLET_USER_CREATED_DESC ON PUBLIC.WALLET_TRANSACTIONS USING BTREE (
	USER_ID DESC NULLS LAST,
	CREATED_AT DESC NULLS LAST,
	TXN_ID DESC NULLS LAST
) TABLESPACE PG_DEFAULT;

CREATE INDEX IF NOT EXISTS IDX_MPH_ITEM_EFF_DESC ON PUBLIC.MEAL_PRICE_HISTORY USING BTREE (
	ITEM_NAME COLLATE PG_CATALOG."default" DESC NULLS LAST,
	EFFECTIVE_FROM DESC NULLS FIRST
) TABLESPACE PG_DEFAULT;

END;