BEGIN;

--------------------------------------------------------------------------------
-- 1. ENUMS
--------------------------------------------------------------------------------
CREATE TYPE PUBLIC.MEAL_TYPE AS ENUM('lunch', 'dinner');

CREATE TYPE PUBLIC.MENU_ITEM_CATEGORY AS ENUM('combo_thali', 'a_la_carte');

CREATE TYPE PUBLIC.TXN_TYPE AS ENUM('recharge', 'delivery', 'refund');

CREATE TYPE PUBLIC.USER_ROLE AS ENUM('customer', 'admin');

CREATE TYPE PUBLIC.SUBSCRIPTION_PLAN AS ENUM('monthly', 'one_off');

--------------------------------------------------------------------------------
-- 2. CORE SYSTEM TABLES
--------------------------------------------------------------------------------
-- Table: USERS
-- Role: Customer profiles and account metadata.
CREATE TABLE PUBLIC.USERS (
	USER_ID INTEGER GENERATED ALWAYS AS IDENTITY,
	NAME TEXT NOT NULL,
	MOBILE_NO TEXT UNIQUE,
	ROLE PUBLIC.USER_ROLE NOT NULL DEFAULT 'customer',
	PLAN PUBLIC.SUBSCRIPTION_PLAN NOT NULL DEFAULT 'one_off',
	CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	CONSTRAINT USERS_PKEY PRIMARY KEY (USER_ID)
);

-- Table: EXPENSES
-- Role: Business outgoings and operational expenditure.
CREATE TABLE PUBLIC.EXPENSES (
	EXPENSE_ID INTEGER GENERATED ALWAYS AS IDENTITY,
	EXPENSE_DATE DATE NOT NULL,
	REASON TEXT NOT NULL,
	AMOUNT NUMERIC(10, 2) NOT NULL CHECK (AMOUNT > 0),
	CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	CONSTRAINT EXPENSES_PKEY PRIMARY KEY (EXPENSE_ID)
);

--------------------------------------------------------------------------------
-- 3. MENU CATALOG & TIMELINE PRICING
--------------------------------------------------------------------------------
-- Table: MENU_ITEMS
-- Role: Master catalog for Thalis and A La Carte items.
CREATE TABLE PUBLIC.MENU_ITEMS (
	ITEM_ID INTEGER GENERATED ALWAYS AS IDENTITY,
	ITEM_NAME TEXT NOT NULL,
	CATEGORY PUBLIC.MENU_ITEM_CATEGORY NOT NULL,
	IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
	CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	CONSTRAINT MENU_ITEMS_PKEY PRIMARY KEY (ITEM_ID),
	CONSTRAINT MENU_ITEMS_ITEM_NAME_KEY UNIQUE (ITEM_NAME)
);

-- Table: MENU_PRICE_SCHEDULE
-- Role: Historical and future pricing log using strictly EFFECTIVE_FROM.
CREATE TABLE PUBLIC.MENU_PRICE_SCHEDULE (
	PRICE_ID INTEGER GENERATED ALWAYS AS IDENTITY,
	ITEM_ID INTEGER NOT NULL,
	PRICE NUMERIC(10, 2) NOT NULL CHECK (PRICE >= 0),
	EFFECTIVE_FROM TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	CONSTRAINT MENU_PRICE_SCHEDULE_PKEY PRIMARY KEY (PRICE_ID),
	CONSTRAINT MENU_PRICE_SCHEDULE_ITEM_FKEY FOREIGN KEY (ITEM_ID) REFERENCES PUBLIC.MENU_ITEMS (ITEM_ID)
);

-- Index for point-in-time price lookups
CREATE INDEX IDX_MENU_PRICE_LOOKUP ON PUBLIC.MENU_PRICE_SCHEDULE (ITEM_ID, EFFECTIVE_FROM DESC);

--------------------------------------------------------------------------------
-- 4. ORDER & FULFILLMENT DOMAIN (OPERATIONS)
--------------------------------------------------------------------------------
-- Table: ORDERS
-- Role: Purchase header tracking user transactions and meal slots.
CREATE TABLE PUBLIC.ORDERS (
	ORDER_ID INTEGER GENERATED ALWAYS AS IDENTITY,
	USER_ID INTEGER NOT NULL,
	ORDER_TIMESTAMP TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	MEAL_TYPE PUBLIC.MEAL_TYPE,
	TOTAL_AMOUNT NUMERIC(10, 2) NOT NULL CHECK (TOTAL_AMOUNT >= 0),
	STATUS TEXT NOT NULL DEFAULT 'completed',
	CONSTRAINT ORDERS_PKEY PRIMARY KEY (ORDER_ID),
	CONSTRAINT ORDERS_USER_FKEY FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS (USER_ID)
);

-- Table: ORDER_ITEMS
-- Role: Detailed line-item breakdown with frozen unit prices.
CREATE TABLE PUBLIC.ORDER_ITEMS (
	ORDER_ITEM_ID INTEGER GENERATED ALWAYS AS IDENTITY,
	ORDER_ID INTEGER NOT NULL,
	ITEM_ID INTEGER NOT NULL,
	QUANTITY INTEGER NOT NULL CHECK (QUANTITY > 0),
	UNIT_PRICE NUMERIC(10, 2) NOT NULL CHECK (UNIT_PRICE >= 0),
	SUBTOTAL NUMERIC(10, 2) NOT NULL CHECK (SUBTOTAL >= 0),
	CONSTRAINT ORDER_ITEMS_PKEY PRIMARY KEY (ORDER_ITEM_ID),
	CONSTRAINT ORDER_ITEMS_ORDER_FKEY FOREIGN KEY (ORDER_ID) REFERENCES PUBLIC.ORDERS (ORDER_ID),
	CONSTRAINT ORDER_ITEMS_ITEM_FKEY FOREIGN KEY (ITEM_ID) REFERENCES PUBLIC.MENU_ITEMS (ITEM_ID)
);

--------------------------------------------------------------------------------
-- 5. WALLET LEDGER DOMAIN (FINANCE & AUDIT)
--------------------------------------------------------------------------------
-- Table: WALLET_TRANSACTIONS
-- Role: Immutable append-only monetary ledger.
CREATE TABLE PUBLIC.WALLET_TRANSACTIONS (
	TXN_ID INTEGER GENERATED ALWAYS AS IDENTITY,
	USER_ID INTEGER NOT NULL,
	TXN_TYPE PUBLIC.TXN_TYPE NOT NULL,
	AMOUNT NUMERIC(10, 2) NOT NULL,
	TXN_TIMESTAMP TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	ORDER_ID INTEGER,
	REFERENCE_ID TEXT,
	CONSTRAINT WALLET_TRANSACTIONS_PKEY PRIMARY KEY (TXN_ID),
	CONSTRAINT WALLET_TXN_USER_FKEY FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS (USER_ID),
	CONSTRAINT WALLET_TXN_ORDER_FKEY FOREIGN KEY (ORDER_ID) REFERENCES PUBLIC.ORDERS (ORDER_ID),
	CONSTRAINT CHK_TXN_TYPE_REF CHECK (
		(
			TXN_TYPE = 'recharge'
			AND ORDER_ID IS NULL
		)
		OR (TXN_TYPE IN ('delivery', 'refund'))
	)
);

--------------------------------------------------------------------------------
-- 6. IMMUTABILITY TRIGGER
--------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION PUBLIC.PREVENT_TRANSACTION_MUTATION () RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'PUBLIC.WALLET_TRANSACTIONS is an immutable ledger. UPDATES and DELETES are strictly prohibited.';
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_PREVENT_TXN_MUTATION BEFORE
UPDATE
OR DELETE ON PUBLIC.WALLET_TRANSACTIONS FOR EACH STATEMENT
EXECUTE FUNCTION PUBLIC.PREVENT_TRANSACTION_MUTATION ();

--------------------------------------------------------------------------------
-- 1. CREATE ROLE (NO SYSTEM-WIDE PRIVILEGES)
--------------------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_user') THEN
        CREATE ROLE app_user WITH
            LOGIN
            NOSUPERUSER
            NOCREATEDB
            NOCREATEROLE
            INHERIT
            NOREPLICATION
            NOBYPASSRLS
            CONNECTION LIMIT -1
            PASSWORD 'Pass_123';
    END IF;
END
$$;

--------------------------------------------------------------------------------
-- 2. ISOLATE DATABASE & SCHEMA PERMISSIONS
--------------------------------------------------------------------------------
-- Deny connection to everything by default, then grant access ONLY to app_db
REVOKE CONNECT ON DATABASE POSTGRES
FROM
	APP_USER;

-- Explicitly grant connection ONLY to your application database
GRANT CONNECT ON DATABASE RANJITAR_RANNAGHOR TO APP_USER;

-- Grant schema-level permissions inside app_db
GRANT USAGE ON SCHEMA PUBLIC TO APP_USER;

--------------------------------------------------------------------------------
-- 3. TABLE-LEVEL LEAST-PRIVILEGE GRANTS
--------------------------------------------------------------------------------
-- USERS
GRANT
SELECT
,
	INSERT,
UPDATE ON TABLE PUBLIC.USERS TO APP_USER;

REVOKE DELETE,
TRUNCATE,
REFERENCES,
TRIGGER ON TABLE PUBLIC.USERS
FROM
	APP_USER;

-- EXPENSES
GRANT
SELECT
,
	INSERT ON TABLE PUBLIC.EXPENSES TO APP_USER;

REVOKE
UPDATE,
DELETE,
TRUNCATE,
REFERENCES,
TRIGGER ON TABLE PUBLIC.EXPENSES
FROM
	APP_USER;

-- MENU_ITEMS
GRANT
SELECT
,
	INSERT,
UPDATE ON TABLE PUBLIC.MENU_ITEMS TO APP_USER;

REVOKE DELETE,
TRUNCATE,
REFERENCES,
TRIGGER ON TABLE PUBLIC.MENU_ITEMS
FROM
	APP_USER;

-- MENU_PRICE_SCHEDULE
GRANT
SELECT
,
	INSERT ON TABLE PUBLIC.MENU_PRICE_SCHEDULE TO APP_USER;

REVOKE
UPDATE,
DELETE,
TRUNCATE,
REFERENCES,
TRIGGER ON TABLE PUBLIC.MENU_PRICE_SCHEDULE
FROM
	APP_USER;

-- ORDERS
GRANT
SELECT
,
	INSERT,
UPDATE ON TABLE PUBLIC.ORDERS TO APP_USER;

REVOKE DELETE,
TRUNCATE,
REFERENCES,
TRIGGER ON TABLE PUBLIC.ORDERS
FROM
	APP_USER;

-- ORDER_ITEMS
GRANT
SELECT
,
	INSERT ON TABLE PUBLIC.ORDER_ITEMS TO APP_USER;

REVOKE
UPDATE,
DELETE,
TRUNCATE,
REFERENCES,
TRIGGER ON TABLE PUBLIC.ORDER_ITEMS
FROM
	APP_USER;

-- WALLET_TRANSACTIONS (Append-only)
GRANT
SELECT
,
	INSERT ON TABLE PUBLIC.WALLET_TRANSACTIONS TO APP_USER;

REVOKE
UPDATE,
DELETE,
TRUNCATE,
REFERENCES,
TRIGGER ON TABLE PUBLIC.WALLET_TRANSACTIONS
FROM
	APP_USER;

--------------------------------------------------------------------------------
-- 4. SEQUENCES & DEFAULT PRIVILEGES
--------------------------------------------------------------------------------
GRANT USAGE,
SELECT
	ON ALL SEQUENCES IN SCHEMA PUBLIC TO APP_USER;

ALTER DEFAULT PRIVILEGES IN SCHEMA PUBLIC
GRANT USAGE,
SELECT
	ON SEQUENCES TO APP_USER;

COMMIT;