-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.daily_logs
(
    log_id serial NOT NULL,
    user_id integer NOT NULL,
    log_date date NOT NULL DEFAULT CURRENT_DATE,
    meal_type shift NOT NULL,
    is_special boolean NOT NULL DEFAULT false,
    special_dish_name text COLLATE pg_catalog."default",
    extra_rice_qty integer NOT NULL DEFAULT 0,
    extra_roti_qty integer NOT NULL DEFAULT 0,
    total_cost numeric(10, 2) NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    has_main_meal boolean DEFAULT true,
    extra_chicken_qty integer DEFAULT 0,
    extra_fish_qty integer DEFAULT 0,
    extra_egg_qty integer DEFAULT 0,
    extra_vegetable_qty integer DEFAULT 0,
    CONSTRAINT daily_logs_pkey PRIMARY KEY (log_id)
);

CREATE TABLE IF NOT EXISTS public.expenses
(
    expense_id serial NOT NULL,
    expense_date date NOT NULL,
    reason text COLLATE pg_catalog."default" NOT NULL,
    amount numeric(10, 2) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT expenses_pkey PRIMARY KEY (expense_id)
);

CREATE TABLE IF NOT EXISTS public.meal_prices
(
    item_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    item_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    price numeric(10, 2) NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT meal_prices_pkey PRIMARY KEY (item_id),
    CONSTRAINT meal_prices_item_name_key UNIQUE (item_name)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id serial NOT NULL,
    name text COLLATE pg_catalog."default",
    mobile_no text COLLATE pg_catalog."default",
    building_no text COLLATE pg_catalog."default",
    room_no text COLLATE pg_catalog."default",
    role user_type DEFAULT 'normal'::user_type,
    plan subscription_type NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.wallet_transactions
(
    txn_id serial NOT NULL,
    user_id integer NOT NULL,
    txn_type txn_type NOT NULL,
    status txn_status NOT NULL DEFAULT 'pending_acknowledgement'::txn_status,
    amount numeric(10, 2) NOT NULL,
    balance_after numeric(10, 2),
    reference_id text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT wallet_transactions_pkey PRIMARY KEY (txn_id)
);

ALTER TABLE IF EXISTS public.daily_logs
    ADD CONSTRAINT daily_logs_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.wallet_transactions
    ADD CONSTRAINT wallet_transactions_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;
